Add more tolerance

diff --git a/deploy-gui b/deploy-gui
--- a/deploy-gui
+++ b/deploy-gui
@@ -30,7 +30,12 @@ else
     exit 1
 fi
 
-# Set up variables.
+# Clean up variables
+for vars in SCRIPT_DIR TEMP LOGFILE DIALOGOPTS CPU_COUNT WORKERS GUNICORN_BIN GUNICONF NGINXCONF NGINXSITE SVCONF SRC_AP USERDOC DBUSER DBPASS DOMNAME INSTPATH SRCDIR; do
+unset $vars
+done
+
+# Set up variables
 SCRIPT_DIR=`pwd`
 TEMP=/tmp
 LOGFILE=/var/log/cynovan.log
@@ -42,6 +47,11 @@ GUNICONF=/etc/gunicorn.d
 NGINXCONF=/etc/nginx
 NGINXSITE=/etc/nginx/sites-available
 SVCONF=/etc/supervisor/conf.d
+
+# Clean up old files in case the last installation failed unexpectedly.
+for files in DBUSER DBPASS DOMNAME INSTPATH SRCDIR; do
+rm $TEMP/$files &> /dev/null
+done
 
 # Install prerequisites
 dialog --title "Installing Prerequisites" \
@@ -67,12 +77,14 @@ clear
 }
 asksrc
 
-[ ! -f $SRC_AP/openerp-wsgi.py ] &&
+while [ ! -f $SRC_AP/openerp-wsgi.py ]; do
 dialog --title "Error occured" \
        --msgbox "$SRC_AP/openerp-wsgi.py not detected.\n\
 Please check your source directory path." \
-       8 70 &&
+       8 70
 asksrc
+done
+clear
 
 # Ask for installation path.
 askinst() {
@@ -81,17 +93,18 @@ dialog --title "OpenERP Installation Path" \
 Default value is /var, if unspecified." \
        8 70 2> $TEMP/INSTPATH
 INSTPATH=`cat $TEMP/INSTPATH`
+[ -z $INSTPATH ] && INSTPATH=/var
 }
 askinst
 
-[ -z $INSTPATH ] && INSTPATH=/var
-[ ! -d $INSTPATH ] &&
+while [ ! -d $INSTPATH ]; do
 dialog --title "Error occured" \
        --msgbox "$INSTPATH is not a valid path.\n\
 Please check your input again." \
-       8 70 &&
-clear
+       8 70
 askinst
+done
+clear
 
 # Ask for database username
 askusername() {
@@ -102,34 +115,50 @@ dialog --title "OpenERP Database User" \
 DBUSER=`cat $TEMP/DBUSER`
 USERDOC=$DBUSER\doc
 clear
+id $DBUSER &> /dev/null
 done
 }
 askusername
 
-[ `id $DBUSER` -ne 0 ] &&
+while [ $? -eq 0 ]; do
+dialog --title "Error occured" \
        --msgbox "Username specified already exists.\n\
 Please choose another username." \
-       8 70 &&
+       8 70
+unset DBUSER
 askusername
+done
+clear
 
 # Ask for database password
+askpassword() {
 while [ -z $DBPASS ]; do
 dialog --title "Password For Database User" \
-       --insecure \  #insecure is an option to show asterisks when input password, otherwise nothing will be shown (to hide how many characters does the password has)
+       --insecure \
        --passwordbox "Please enter the password for database login role '$DBUSER'." \
        8 70 2> $TEMP/DBPASS
 DBPASS=`cat $TEMP/DBPASS`
 rm $TEMP/DBPASS
-clear
+done
+}
+askpassword
+
+while [ ${#DBPASS} -lt 8 ]; do
+dialog --title "Error occured" \
+       --msgbox "Password must be at least 8 characters long.\n\
+Please use another password." \
+       8 70
+unset DBPASS
+askpassword
 done
 
 # Ask for system domain name
 dialog --title "System Domain Name" \
        --inputbox "Please enter the domain name for this machine.\n\
-Default value is localhost, if unspecified." \
+Default value is `hostname`, if unspecified." \
        8 70 2> $TEMP/DOMNAME
 DOMNAME=`cat $TEMP/DOMNAME`
-[ -z $DOMNAME ] && DOMNAME=localhost
+[ -z $DOMNAME ] && DOMNAME=`hostname`
 clear
 
 INSPROG=0
@@ -241,7 +270,7 @@ dialog --title "OpenERP Installation" \
 
 # Clean up
 for files in DBUSER DOMNAME INSTPATH SRCDIR; do
-rm $TEMP/$files
+rm $TEMP/$files &> /dev/null
 done
 
 # Print finish dialog
